#!/usr/bin/env bash

count=0
disconnected=%{F#ffffff}"󰤮"%{F-}
wireless_connected=%{F#ffffff}"󰖩"%{F-}
ethernet_connected=""

#idname="$(iwgetid | cut -d \" -f2)"
#wifiname=%{F#a3be8c}$idname%{F-}

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 0.5
    fi
done
