#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb ~/.Xresources
$HOME/.config/polybar/launch.sh

picom &

dunst &

mpd &

feh --bg-fill /home/tuxm/Pictures/wallpapers/benord.png

#$HOME/.config/polybar/launch.sh 
#$polybar top-panel -c ~/.config/polybar/drac.sh
#polybar top-panel -c ~/anotherlie/polybar/drac.sh
#xrdb ~/.Xresources
/usr/bin/lxpolkit &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d Home Web Work Misc 

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a urxvt desktop='^1'follow=on focus=on

xsetroot -cursor_name left_ptr &

# border colors
#bspc config focused_border_color "#83a598"
bspc config focused_border_color "#F8BB2E"
bspc config normal_border_color "#454849"



